if Harvest == nil then Harvest = {} end

--zones
Harvest.poiData = {
   ["alikr"] = {},      --Alik'r Desert
   ["auridon"] = {},    --Auridon, Khenarthi's Roost
   ["bangkorai"] = {},  --Bangkorai
   ["coldharbor"] = {}, --Coldharbour
   ["cyrodiil"] = {},   --Cyrodiil
   ["deshaan"] = {},    --"Deshaan"
   ["eastmarch"] = {},  --Eastmarch
   ["glenumbra"] = {},  --Glenumbra, Betnikh, Stros M'Kai
   ["grahtwood"] = {},  --Grahtwood
   ["greenshade"] = {}, --Greenshade
   ["malabaltor"] = {}, --Malabal Tor
   ["reapersmarch"] = {},  --Reaper's March
   ["rivenspire"] = {}, --Rivenspire
   ["shadowfen"] = {},  --Shadowfen
   ["stonefalls"] = {}, --Stonefalls, Bal Foyen, Bleakrock Isle
   ["stormhaven"] = {}, --Stormhaven
   ["therift"] = {},    --The Rift
   ["craglorn"] = {},    --The Rift
}

--subzone
Harvest.poiData["alikr"] = {
--Alik'r Desert (Daggerfall, lvl 31-37)
   ["alikr_base"] = {            --Alik'r Desert
      --fr
      { "Aldunz^M", 3 },
      { "Alezer Kotu^F", 9 },
      { "Port-grison^M", 8 },
      { "oasis de l'Artisan^fd", 9 },
      { "oratoire des écuries d'Aswala^md", 1 },
      { "remembrance d'Aswala^fd", 2 },
      { "Bergame^F", 8 },
      { "oratoire de Bergame^md", 1 },
      { "excavations de Froideroche", 3 },
      { "mine du chagrin de Divad^fd", 3 },
      { "oratoire de la mine du chagrin de Divad^md", 1 },
      { "tertres de l'éventreur des dunes^pmd", 2 },
      { "Donjon : Volenfell^M", 7 },
      { "pic esteron^md", 2 },
      { "caverne des cœurs perdus^fd", 6 },
      { "campement du géant^md", 6 },
      { "oratoire de l'oasis de la tête de bouc^md", 1 },
      { "camp des harfreuses^md", 6 },
      { "campement d'Hatiha^md", 2 },
      { "dolmen des landes creuses^md",  5},
      { "guet d'HoonDing^md",  8},
      { "oratoire du guet d'HoonDing^md", 1 },
      { "repos du roi^md", 6 },
      { "Kozanset^M", 8 },
      { "mines de Kulati^pfd", 8 },
      { "oratoire des mines de Kulati^md", 1 },
      { "lame de Léki^fd", 8 },
      { "oratoire de la lame de Léki^md", 1 },
      { "cercle inférieur^md", 6 },
      { "caravane perdue^fd", 6 },
      { "cité perdue des Na-Totambu^fd", 3 },
      { "manne de Morwha^fd", 8 },
      { "oratoire de la manne de Morwha^md", 1 },
      { "nécropole de Motalion^fd", 8 },
      { "dolmen de Myrkwasa^md", 5 },
      { "berge des Na-Totambu^fd", 2 },
      { "falaise des ogres^md", 8 },
      { "Ragnthar^F", 2 },
      { "champs des capte-pluie^mpd", 8 },
      { "Rkulftzel^M", 9 },
      { "Salas En^M", 8 },
      { "campement de la milice de Marchesel^md", 2 },
      { "mine des Décapés^fd", 3 },
      { "Santaki^M", 3 },
      { "Satakalaam^F", 8 },
      { "oratoire de Satakalaam^md", 1 },
      { "Sentinelle^F", 8 },
      { "alikr,17, quais de Sentinelle^pmd", 8 },
      { "oratoire de Sentinelle^md", 1 },
      { "échine de Sep^fd", 8 },
      { "oratoire de l'échine de Sep^md", 1 },
      { "oratoire de l'Aire des Gritches^md", 1 },
      { "bénédiction de Tava^fd", 8 },
      { "larmes des déshonorés^pfd", 8 },
      { "Rituel^md", 4 },
      { "Voleur^md", 4 },
      { "Guerrier^md", 4 },
      { "dolmen de Tigonus^md", 5 },
      { "trône de Tu'whacca^md", 8 },
      { "quai du voyageur^md", 2 },
      { "Yldzuun^M", 3 },
   },
}

Harvest.poiData["auridon"] = {
--Auridon (Aldmeri lvl 5-15)
   ["auridon_base"] = { --Auridon
     --fr
     {"chutes du fanal^fd", 9 },
     {"Bewan^F", 3 },
     {"île de Buraniim^fd", 2 },
     {"dolmen de Kalembar^md", 5 },
     {"château Rilis^md", 8 },
     {"École de maintien aldmeri^fd", 8 },
     {"oratoire de l'école^md", 1 },
     {"Aubeneuve^F", 8 },
     {"concession de Del^fd", 3 },
     {"Donjon : Le Cachot interdit", 7 },
     {"campement des îlots d'Esterive^md", 9 },
     {"folie d'Entila^fd", 3 },
     {"île d'Errinorne^fd", 2 },
     {"Ezduiin^M", 8 },
     {"Prime-Tenure^M", 8 },
     {"oratoire de Prime-Tenure^md", 1 },
     {"val miroitant^md", 8 },
     {"anse d'Émeraigues^fd", 8 },
     {"oratoire d'Émeraigues", 1 },
     {"invocations hérétiques^pfd", 6 },
     {"camp d'entraînement de l'Héritage^md", 6 },
     {"fort de la marée haute^md", 9 },
     {"dolmen de Lluvamir^md", 5 },
     {"île de la Contemplation^fd", 2 },
     {"campement d'invasion maormer^md", 2 },
     {"Mathiisen^M", 8 },
     {"oratoire de Mathiisen^md", 1 },
     {"rancœur de Mérunès^fd", 3 },
     {"repos du singe^md", 2 },
     {"antre de la Couveuse^md", 6 },
     {"accostage de Neuf-Proues^md", 2 },
     {"fanal nord^md", 8 },
     {"Ondil^M", 3 },
     {"Phaer^F", 8 },
     {"oratoire de Phaer^md", 1 },
     {"Quendeluun^F", 8 },
     {"oratoire de Quendeluun^md", 1 },
     {"campement de l'escarpe côtière^md", 6 },
     {"Bosquet brisé^md", 8 },
     {"Silsailen^F", 8 },
     {"Gardeciel^M", 8 },
     {"oratoire de Gardeciel^md", 1 },
     {"anse du trafiquant^fd", 2 },
     {"plateau du creuset des âmes^md", 6 },
     {"fanal sud^md", 8 },
     {"Tanzelwil^M", 8 },
     {"oratoire de Tanzelwil^md", 1 },
     {"port^md", 1 },
     {"Dame^fd", 4 },
     {"Amant^md", 4 },
     {"ravine du Chicot^fd", 8 },
     {"Torinaan^M", 8 },
     {"dolmen de Vafe^md", 5 },
     {"quais de Vulkhel^pmd", 8 },
     {"Guet de Vulkhel^md", 8 },
     {"oratoire du guet de Vulkhel^md", 1 },
     {"Wansalen^M", 3 },
     {"oratoire du val venteux^md", 1 },
     {"épave du Rapace^fd", 6 },
     
   },
--Khenarthi's Roost (Aldmeri, lvl 1-5)
   ["khenarthisroost_base"] = {  --Khenarthi's Roost
     --fr
     {"campement de chasse de Bolga^md", 2 },
     {"quai de l'Œil-de-chat^md", 8 },
     {"détroit de l'Aigle^md", 2 },
     {"cuvette d'Hazak^fd", 8 },
     {"oratoire du perchoir de Khenarthi^md", 1 },
     {"plantation des Lunes rieuses^fd", 8 },
     {"Mistral^M", 8 },
     {"oratoire de Mistral^md", 1 },
     {"réconfort de Rid-Thar^md", 2 },
     {"ressac des veuves^md", 8 },
     {"plantation de la Coquille mouchetée^fd", 8 },
     {"temple des Lunes croissantes^md", 2 },
     {"temple de la Lune noire^md", 2 },
     {"temple des Sources du deuil^md", 8 },
     {"temple de la Danse des deux Lunes^md", 2 },
     {"plantation Troussevent^fd", 8 },
     
   },
}



Harvest.poiData["bangkorai"] = {
--Bangkorai (Daggerfall, lvl 37-43)
   ["bangkorai_base"] = {        --Bangkorai
     --fr
     {"sanctuaire d'Arlimahéra^md", 6 },
     {"oasis Ash'abah^fd", 3 },
     {"garnison de Bangkoraï^fd", 8 },
     {"oratoire du col de Bangkoraï^md", 1 },
     {"terrains de chauffe^pmd", 3 },
     {"île flétrie^fd", 6 },
     {"crypte des Exilés^fd", 4 },
     {"ferme Damar^fd", 22 },
     {"Donjon : havre de Cœurnoir^md", 7 },
     {"oratoire oriental d'Abondance^md", 1 },
     {"dolmen d'Éphèse^md", 5 },
     {"Abondance^F", 8 },
     {"oratoire d'Abondance^md", 1 },
     {"grotte effondrée^fd", 8 },
     {"dolmen des landes désolées^md", 5 },
     {"roc de Gjarma^md", 2 },
     {"lac Halcyon^md", 8 },
     {"oratoire du lac Halcyon^md", 1 },
     {"panthéon des Héros^md", 8 },
     {"Gloire d'Hallin^fd", 8 },
     {"oratoire de la Gloire d'Hallin^md", 1 },
     {"recoin du Hurleur^md", 2 },
     {"crique des Choucas^fd", 8 },
     {"creux de Kerbol^md", 8 },
     {"Klathzgar^F", 3 },
     {"tour de Lacquevue^fd", 6 },
     {"gué du Martyr^md", 8 },
     {"dolmen de Mournoth^md", 5 },
     {"hameau de Murcien^md", 8 },
     {"chutes de Nilata^pfd", 6 },
     {"ruines de Nilata^pfd", 8 },
     {"oratoire des ruines de Nilata^md", 1 },
     {"Norval^md", 8 },
     {"vieille Tour^fd", 8 },
     {"oratoire de la vieille Tour^md", 1 },
     {"souffle d'Onsi^md", 8 },
     {"oratoire du souffle d'Onsi^md", 1 },
     {"cimetière de Pélin^md", 8 },
     {"ruines de Qharroa^pfd", 8 },
     {"Roue de Razak^fd", 3 },
     {"Remblai des gravats^md", 3 },
     {"sources sacrées^pfd", 2 },
     {"ruines de Silasselli^pfd", 9 },
     {"accostage de Strastnoc^md", 2 },
     {"camp de l'invocateur^md", 6 },
     {"route encaissée^fd", 8 },
     {"oratoire de la route encaissée^md", 1 },
     {"ruines de Télésubi^pfd", 6 },
     {"Apprenti^md", 4 },
     {"Les pourparlers", 8 },
     {"Destrier^md", 4 },
     {"mépris de Torog^md", 3 },
     {"Cure-dents à trolls^md", 3 },
     {"oratoire du Cure-dents à trolls^md", 1 },
     {"cachette viride^fd", 9 },
     {"Guet viride^md", 3 },
     {"bois virides^pmd", 8 },
     {"oratoire des bois virides^md", 1 },
     {"fissure de Wethers^fd", 9 },
     {"repos de Yanurah^md", 2 },
   },
}

Harvest.poiData["coldharbor"] = {
--Coldharbour (all, lvl 45-50)
   ["coldharbour_base"] = {      --Coldharbour
     --fr
     {"Aba-Darre^F", 6 },
     {"Aba-Loria^F", 3 },
     {"cahute de Cadwell^fd", 2 },
     {"Falaises du désastre^pfd", 8 },
     {"Cour de l'outrage^fd", 8 },
     {"oratoire de la Cour de l'outrage^md", 1 },
     {"bosquet de Cynhamoth^md", 6 },
     {"garde-manger de daedroth^md", 6 },
     {"antre de Tissemort^md", 9 },
     {"Donjon : Chambres de la folie^md", 7 },
     {"champ du massacre de Duriatundur^md", 6 },
     {"surplomb infini^md", 2 },
     {"oratoire de l'Escalier infini^md", 1 },
     {"oratoire du Pichet sans fond^md", 1 },
     {"maison de la guilde des guerriers^fd", 2 },
     {"fontaine des manigances^fd", 9 },
     {"village abandonné^md", 2 },
     {"oratoire des Grands Fers^md", 1 },
     {"Haj Uxith^M", 8 },
     {"oratoire de Haj Uxith^md", 1 },
     {"oratoire de la Cité creuse^md", 1 },
     {"Bibliothèque crépusculaire^fd", 8 },
     {"oratoire de la Bibliothèque crépusculaire^md", 1 },
     {"maison de la guilde des mages^fd", 2 },
     {"tombeau de Mal Sorra^md", 3 },
     {"oratoire du manoir des réjouissances^md", 1 },
     {"oratoire de l'Étendue asélène^md", 1 },
     {"oratoire de la Citadelle de l'écorcheur^md", 1 },
     {"cour des revenants^fd", 6 },
     {"autel à Kyne^md", 2 },
     {"oratoire des Plaines voilées^md", 1 },
     {"Pic répudié^md", 8 },
     {"campement du survivant^md", 2 },
     {"Forge noire^fd", 8 },
     {"Grotte aux trophées^fd", 3 },
     {"Abîme^fd", 8 },
     {"oratoire de l'Abîme^md", 1 },
     {"Escalier infini^md", 8 },
     {"Pichet sans fond^md", 8 },
     {"Grands Fers^mpd", 8 },
     {"grotte de la dépravation^fd", 3 },
     {"Cité creuse^fd", 8 },
     {"Oubliettes obscures^pfd", 8 },
     {"Flotte perdue^fd", 8 },
     {"manoir des réjouissances^md", 8 },
     {"Étendue asélène^fd", 8 },
     {"Verger^md", 8 },
     {"oratoire du Verger^md", 1 },
     {"Citadelle de l'écorcheur^fd", 8 },
     {"Laboratoire infâme^md", 8 },
     {"gorge plaintive^fd", 3 },
     {"Tour des mensonges^fd", 8 },
     {"Chambre-forte de Haman Forgefeu^fd", 3 },
     {"Village des perdus^md", 3 },
     {"creux de Zemarek^md", 6 },
   },
}

Harvest.poiData["cyrodiil"] = {
--Cyrodiil (all, lvl 10+)
   ["ava_whole"] = {          --Cyrodiil
     --fr
     {"verger abandonné^md", 2 },
     {"abbaye des Huit^fd", 2 },
     {"Anga^F", 2 },
     {"dolmen du bois de Guettepomme^md", 5 },
     {"caverne désolée^fd", 2 },
     {"Belda^F", 2 },
     {"caverne du Crin-de-Sang^fd", 3 },
     {"caverne de l'À-pic^fd", 3 },
     {"Bruma^F", 8 },
     {"propriété brûlée^fd", 2 },
     {"caverne de Cappière^fd", 3 },
     {"Ceyatatar^F", 2 },
     {"Cheydinhal^M", 8 },
     {"dolmen des contreforts de Cheydinhal^md", 5 },
     {"Chorrol^M", 8 },
     {"temple du roi des nuages^md", 5 },
     {"ruine de Froidmaïs^fd", 2 },
     {"caverne du Bois fendu^fd", 3 },
     {"redoute du Doigt tors^md", 2 },
     {"Gué-les-Champs^M", 8 },
     {"Calárith^F", 2 },
     {"oratoire de la porte est d'Elsweyr^md", 1 },
     {"dolmen de la côte est^md", 5 },
     {"caverne aux échos^fd", 3 },
     {"tour de l'Empire^fd", 2 },
     {"Fanacas^M", 2 },
     {"Fanacastul^M", 2 },
     {"avant-poste de la Vipère grise^md", 2 },
     {"dolmen de la Grande Forêt^md", 5 },
     {"dolmen de Vertepâtures^md", 5 },
     {"Tailleterre^M", 2 },
     {"guet d'Harlun^md", 2 },
     {"caverne de Paillenote^fd", 3 },
     {"propriété Hedoran^fd", 2 },
     {"camp des Collines^md", 2 },
     {"ruines de la Ferme^pfd", 2 },
     {"caverne hurlante^fd", 2 },
     {"val de Hrotanda^md", 2 },
     {"foyer de Cœurgel^md", 2 },
     {"chute de Juras^fd", 2 },
     {"caverne des Armoiries^fd", 3 },
     {"ruine du lac brumeux^fd", 2 },
     {"Lindai^F", 2 },
     {"lac de Bergesable^md", 3 },
     {"quais du Croc lunaire^pmd", 2 },
     {"doléance de Moffka^fd", 2 },
     {"Moranda^F", 2 },
     {"caverne de Valboue^fd", 3 },
     {"Nagastani^M", 2 },
     {"Narsinfel^F", 2 },
     {"caverne aux tritons^fd", 3 },
     {"dolmen du bassin de Niben^md", 5 },
     {"dolmen de la vallée de Nibenay^md", 5 },
     {"Ninendava^F", 2 },
     {"caverne de Nisin^fd", 3 },
     {"Nornal^F", 2 },
     {"Nornalhorst^F", 2 },
     {"oratoire de la porte nord de Morrowind^md", 1 },
     {"oratoire de la porte nord de Hauteroche^md", 1 },
     {"dolmen de la côte nord-ouest^md", 5 },
     {"Piukanda^F", 2 },
     {"cavernes criblées^pfd", 3 },
     {"caverne de l'Eau-vive^fd", 3 },
     {"caverne du rubis rouge^fd", 3 },
     {"Guettecours^M", 2 },
     {"Sardavar Leed^M", 2 },
     {"Sédor^M", 2 },
     {"Sercen^F", 2 },
     {"caverne du creux du serpent^fd", 3 },
     {"propriété du clan Shurgak^fd", 2 },
     {"oratoire de la porte sud de Hauteroche^md", 1 },
     {"oratoire de la porte sud de Morrowind^md", 1 },
     {"temple des Phalènes ancestrales^md", 2 },
     {"chai de Thalara^md", 2},
     {"Apprenti^md", 4 },
     {"Atronach^md", 4 },
     {"Dame^fd", 4 },
     {"Amant^md", 4 },
     {"Mage^md", 4 },
     {"Rituel^md", 4 },
     {"Serpent^md", 4 },
     {"Ombre^fd", 4 },
     {"The Steed", 4 },
     {"Voleur^md", 4 },
     {"Tour^fd", 4 },
     {"Guerrier^md", 4 },
     {"creux du champignon vénéneux^md", 3 },
     {"caverne du sous-suaire^fd", 3 },
     {"Vahtacen^M", 3 },
     {"Vlastarus^M", 8 },
     {"mine côtière^fd", 2 },
     {"Wenyandawik^M", 2 },
     {"oratoire de la porte ouest d'Elsweyr^md", 1 },
     {"Weye^F", 2 },
     {"prieuré de Weynon^md", 2 },
     {"montagnes aux chutes blanches^pfd", 2 },
     {"chai de Wilminn^md", 2 },
     {"dolmen d'Hivrallonge^md", 5 },
     {"vigie de la Main de bois^fd", 2 },
     {"chai de Zimar^md", 2 },
     
   },
}




Harvest.poiData["deshaan"] = {
--Deshaan (Ebonheart, lvl 16-23)
   ["deshaan_base"] = {          --"Deshaan"
      --fr
      { "ferme d'Avatan^fd", 9},
      { "mine de Berezan^fd", 9},
      { "Bthanual^F", 8},
      { "crête de la caravane^fd", 6},
      { "plateau de la Voie reptilienne^md", 2},
      { "mine de Roc-fosse^fd", 8},
      { "Ronçaire terrible^md", 6},
      { "autel rituel de Druitularg^md", 6},
      { "Donjon : cavernes d'Ombre-noire^M", 7},
      { "gouffre d'Eidolon^md", 8},
      { "oratoire du gouffre d'Eidolon^md", 1},
      { "cryptes oubliées^pfd", 3},
      { "oratoire de l'Esprit du serpent^md", 1},
      { "bosquet de l'Abomination^md", 6},
      { "cahute de Hlanii^fd", 2},
      { "ferme de la maison Drès^fd", 2},
      { "grotte du Lobe aigu^fd", 3},
      { "abri de dame Llarel^md", 3},
      { "dolmen de Lagomère^md", 5},
      { "retraite du lac Hlaalu^fd", 9},
      { "Bas-Bthanual^M", 3},
      { "cercle funéraire de Mabrigash^md", 6},
      { "gouffre de Malak^md", 8},
      { "Longsanglot^F", 8},
      { "oratoire de Longsanglot^md", 1},
      { "Muth Gnaar^F", 8},
      { "oratoire des collines de Muth Gnaar^md", 1},
      { "Mzithumz^F", 8},
      { "oratoire de Mzithum^md", 1},
      { "Narsis^F", 8},
      { "gorge d'obsidienne^fd", 8},
      { "oratoire de la gorge d'obsidienne^md", 1},
      { "maison de la vieille Ida^fd", 2},
      { "zone de quarantaine du Serk^fd", 8},
      { "oratoire de la zone de quarantaine^md", 1},
      { "dolmen de Hume-Terre^md", 5},
      { "quai de Rédoran^md", 2},
      { "Selfora^F", 8},
      { "oratoire de Selfora^md", 1},
      { "Shad Astula^F", 8},
      { "oratoire de Shad Astula^md", 1},
      { "butte de Courte-broche^fd", 6},
      { "sanctuaire de saint Véloth^md", 8},
      { "autel à saint Rilms^md", 2},
      { "Marais paisible^md", 8},
      { "oratoire du Marais paisible^md", 1},
      { "dolmen de Siltreen^md", 5},
      { "faille du contrebandier^fd", 2},
      { "fort Tal'Deic^M", 8},
      { "oratoire des Terres de Tal'Deic^md", 1},
      { "pic de Taléon^md", 3},
      { "jardin des dépouilles^md", 3},
      { "Seigneur^md", 4},
      { "Mage^md", 4},
      { "Tour^fd", 4},
      { "temple du Tribunal^md", 8},
      { "mine du Triple Cercle^fd", 3},
      { "vallon de l'Esprit du serpent^md", 8},
      { "oratoire de Narsis Ouest^md", 1}
   },
}


Harvest.poiData["eastmarch"] = {
--Eastmarch (Ebonheart, lvl 31-37)
   ["eastmarch_base"] = {        --Eastmarch
      --fr
      { "fierté d'Ammabani^fd", 6 },
      { "campement de Lame-amère^md", 2 },
      { "Crête de l'ossuaire^fd", 8 },
      { "Berceroc^M", 8 },
      { "oratoire de Berceroc^md", 1 },
      { "Bourberoc^M", 8 },
      { "grotte de Bourberoc^fd", 2 },
      { "atelier cavernicole de Kada l'Écarlate^md", 9 },
      { "gué de Sombreflot^md", 2 },
      { "mont-du-dragon^md", 6 },
      { "sanctille du Dragon^fd", 6 },
      { "Donjon : donjon d'Affregivre", 7 },
      { "fort Amol^M", 8 },
      { "oratoire de fort Amol^md", 1 },
      { "fort Morvunskar^M", 8 },
      { "oratoire de fort Morvunskar^md", 1 },
      { "dolmen de la toundra d'Aigues-givre^md", 5 },
      { "cœur du géant^md", 2 },
      { "dolmen du ru des Géants^md", 5 },
      { "Nécropole^fd", 3 },
      { "Massemaison^F", 9 },
      { "cachette de l'Ermite^fd", 2 },
      { "chambre de Glacemartel^fd", 3 },
      { "dolmen des pics de Glacevent^md", 5 },
      { "redoute de Jorunn^fd", 8 },
      { "oratoire de la Redoute de Jorunn^md", 1 },
      { "Bosquet de Kyne^md", 8 },
      { "oratoire du Bosquet de Kyne^md", 1 },
      { "oratoire du camp de bûcherons^md", 1 },
      { "grotte du Couteau perdu^fd", 8 },
      { "Bas-Yorgrim^md", 8 },
      { "Arquebrumes^F", 8 },
      { "oratoire d'Arquebrumes^md", 1 },
      { "Mzulft^F", 8 },
      { "caverne du vieux Sord^fd", 3 },
      { "tanière de Ragegriffe^fd", 6 },
      { "Ragnthar^F", 2 },
      { "ronde de la Ratière^fd", 6 },
      { "Skuldafn^M", 8 },
      { "oratoire de Skuldafn^md", 1 },
      { "crypte de Cime-foudre^fd", 3 },
      { "camp des Vive-lames^md", 6 },
      { "Guinguette du thane Jeggi^fd", 2 },
      { "tombe du Bâtard^fd", 3 },
      { "Grotte aux frimas^fd", 3 },
      { "Grotte froide^fd", 3 },
      { "Rituel^md", 4 },
      { "Voleur^md", 4 },
      { "Guerrier^md", 4 },
      { "camp de bûcherons de Thulvald^md", 8 },
      { "atelier du ferblantier Tobin^md", 9 },
      { "oratoire de l'hydromellerie de Voljar^md", 1 },
      { "hydromellerie de Voljar^fd", 8 },
      { "Vendeaume^F", 8 },
      { "oratoire de Vendeaume^md", 1 },
      { "Wittestadr^M", 8 },
      { "oratoire de Wittestadr^md", 1 },
      
   },
}

Harvest.poiData["glenumbra"] = {
--Glenumbra (Daggerfall, lvl 5-15)
   ["glenumbra_base"] = {        --Glenumbra
    --fr
    { "Métaye-la-Vieille^F", 8},
    { "oratoire de Métaye-la-Vieille^md", 1},
    { "sanctuaire du Malandrin^md", 3},
    { "piton de Bael^md", 8},
    { "oratoire du piton de Bael^md", 1},
    { "île de la lancefeu^fd", 6},
    { "arbre du Wyrd de Beldama^md", 8},
    { "tertres funéraires^mp", 8},
    { "oratoire des tertres funéraires^md", 1},
    { "dolmen des collines de Cambray^md", 5}, 
    { "col de Cambray^md", 8},
    { "Camlorn^F", 8},
    { "Cath Bedraud^F", 8}, 
    { "maison des frissons^fd", 9},
    { "Croissalant^M", 8},
    { "oratoire de Croissalant^md", 1}, 
    { "fort de Veillecaveau^md", 3},
    { "dolmen de Daénia^md", 5},
    { "Daguefilante^F", 8},
    { "quais sud de Daguefilante^pm", 8}, 
    { "oratoire de Daguefilante^md", 1},
    { "scierie de Deleyn^fd", 8}, 
    { "oratoire de la scierie de Deleyn^md", 1}, 
    { "île Pierrefroide^fd", 2},
    { "donjon de Drèsan^md", 8},
    { "Donjon : Tressefuseau^md", 7}, 
    { "ruines de Dwynnarth^pfd", 8},
    { "Aigle-sur-rive^M", 8},
    { "oratoire d'Aigle-sur-rive^md", 1}, 
    { "crypte d'ébène^fd", 3},
    { "Enduum", 3},
    { "oratoire de Longueveille^md", 1}, 
    { "ferme Gaudet^fd", 2},
    { "landes de Glénumbrie^pfd", 8},
    { "marais aux harfreuses^md", 8},
    { "oratoire du marais aux harfreuses^md", 1}, 
    { "tour d'Ilessan^fd",  3},
    { "dolmen de la Garde royale^md", 5}, 
    { "bastion de la garde du Lion^md", 8},
    { "oratoire du bastion de la garde du Lion^md", 1}, 
    { "folie de Mérovec^fd", 2},
    { "tour de Mésanthano^fd", 9},
    { "cabane de pêche de Miltrin^fd", 2}, 
    { "mines de Khuras^pfd", 3},
    { "chutes enlisées^pfd", 2},
    { "oratoire du marais aux harfreuses nord^md", 1}, 
    { "pointe de la côte nord^fd", 6},
    { "Par Molag^F", 9},
    { "camp des Freux écarlates^m", 8}, 
    { "panorama de la côte^md", 6},
    { "Sillon hurlant^md", 8}, 
    { "Silumm^F", 3},
    { "Entrécif^M", 2},
    { "port^md", 1}, 
    { "Dame^fd", 4},
    { "Amant^md", 4},
    { "camp du loup^md", 6},
    { "tombe des rois perdus^fd", 8},
    { "crique de Gueule d'acier^fd", 6},
    { "val des gardiennes^md", 8},
    { "tour Guetteval^fd", 2},
    { "surplomb ouest^md", 6},
    { "Ouestrie^F", 8},
    { "oratoire de l'arbre du Wyrd^md", 1}
    
   },
--Betnikh (Daggerfall, lvl 1-5)
   ["betnihk_base"] = {
      --fr
      { "Collines gravées^pfd", 8 },
      { "oratoire des Collines gravées^md", 1 },
      { "Chute de Carzog^F", 8 },
      { "Éyéarata^F", 2 },
      { "recoin de Gilbard^md", 2 },
      { "Sombrechamp^M", 8 },
      { "oratoire de Sombrechamp^md", 1 },
      { "Moriseli", 8 },
      { "oratoire de Pierrecroc^md", 1 },
   },
--Stros M'Kai (Daggerfall, lvl 1-5)
   ["strosmkai_base"] = {
      --fr
      { "Bthzark^M", 8 },
      { "campement gobelin Dévorechien^md", 2 },
      { "pilier du soleil chantant^md", 2 },
      { "Port Hunding^M", 8 },
      { "oratoire de Port Hunding^md", 1 },
      { "précipice du marchand intrépide^md", 2 },
      { "Port des saints^M", 8 },
      { "oratoire du Port des saints^md", 1 },
      { "oratoire de la grotte ensablée^md", 1 },
      { "La Tombe^F", 8 },
      
   },
}

Harvest.poiData["grahtwood"] = {
--Grahtwood (Aldmeri, lvl 16-23)
   ["grahtwood_base"] = {        --Grahtwood
      --fr
      { "mémorial à la bataille de Cormont^md", 2 },
      { "surplomb de la ruée du sanglier^md", 2 },
      { "verger des ossements^md", 8 },
      { "Fougereau^F", 8 },
      { "mine à kwamas de Boguerave^fd", 3 },
      { "caverne des voiles brisées^fd", 8 },
      { "Cormont^F", 8 },
      { "oratoire de Cormont^md", 1 },
      { "Donjon : creuset des aînés^m", 7 },
      { "Faneracine^F", 8 },
      { "oratoire du temple de Faneracine^md", 1 },
      { "oratoire de Faneracine^md", 1 },
      { "site hivernal de Falinesti^md", 8 },
      { "oratoire du site hivernal de Falinesti^md", 1 },
      { "mine de Faltonia^fd", 2 },
      { "île du pêcheur^fd", 9 },
      { "campement de la racine fourchue^md", 2 },
      { "Gil-Var-Delle^F", 8 },
      { "oratoire de Gil-Var-Delle^md", 1 },
      { "Or-Fol^M", 8 },
      { "oratoire du bourbier gris^md", 1 },
      { "dolmen de la Salle verte^md", 5 },
      { "Havre^F", 8 },
      { "oratoire de Havre^md", 1 },
      { "cromlech d'Hircine^md", 6 },
      { "Karthdar^M", 8 },
      { "marais de dame Consoline^md", 6 },
      { "Laéloria^F", 8 },
      { "dolmen de la longue côte^md", 5 },
      { "mine de Mobar^fd", 3 },
      { "Ne Salas^M", 3 },
      { "perchoir de Nindaeril^md", 6 },
      { "ossuaire de Télacar^md", 8 },
      { "oratoire de l'ossuaire^md", 1 },
      { "campement du braconnier^md", 6 },
      { "comptoir de commerce de Rougepel^md", 8 },
      { "oratoire de Rougepel^md", 1 },
      { "reliquaire des étoiles^md", 8 },
      { "promontoire de Réman^md", 8 },
      { "ruines de Scinderacine^pfd", 3 },
      { "grotte du saut sacré^fd", 2 },
      { "Pointe-Sud^F", 8 },
      { "oratoire de Pointe-Sud^md", 1 },
      { "cottage de la brise^md", 2 },
      { "campement de bandits de Tarlain^md", 2 },
      { "dolmen du faîte de Tarlain^md", 5 },
      { "temple des Huit^md", 9 },
      { "bourbier gris^md", 8 },
      { "Seigneur^md", 4 },
      { "Mage^md", 4 },
      { "fosse aux grattements^fd", 3 },
      { "Tour^fd", 4 },
      { "caverne de Thugrub^fd", 6 },
      { "repos de Valanir^md", 6 },
      { "caverne de Roncemort^fd", 3 },
      { "loge d'Ombronce^fd", 9 },
      { "profondeurs de Verracine^pfd", 3 },
      
   },
}

Harvest.poiData["greenshade"] = {
--Greenshade (Aldmeri lvl 25-30)
   ["greenshade_base"] = {       --Greenshade
      --fr
      { "Arananga^M", 9 },
      { "Tranchée du tertre^fd", 3 },
      { "Roncebrèche^F", 8 },
      { "campement Gushnukbur^md", 2 },
      { "Carac Dena^F", 3 },
      { "Vullain l'effroi^M", 8 },
      { "col de Driladan^md", 8 },
      { "dolmen de la côte engloutie^md", 5 },
      { "Donjon : Cité des cendres^md", 7 },
      { "mare à l'écho^fd", 2 },
      { "site printannier de Falinesti^md", 8 },
      { "oratoire de Falinesti^md", 1 },
      { "repos du pêcheur^md", 2 },
      { "bourbier de Gathongor^md", 6 },
      { "dolmen de la moelle du Vert^md", 5 },
      { "Vercors^M", 8 },
      { "oratoire de Vercors^md", 1 },
      { "mine de Gurzag^fd", 3 },
      { "tanière de l'Haridelle^fd", 3 },
      { "Hectahame^M", 8 },
      { "antre creux^md", 2 },
      { "Labyrinthe^md", 8 },
      { "oratoire du Labyrinthe^md", 1 },
      { "étang de Lanalda^md", 9 },
      { "campement maormer^md", 6 },
      { "Marbruk^F", 8 },
      { "oratoire de Marbruk^md", 1 },
      { "Lunehenge^M", 8 },
      { "oratoire de Lunehenge^md", 1 },
      { "Naril Nagaïa^F", 3 },
      { "Pelda Tarn^F", 6 },
      { "campement de reconnaissance^md", 6 },
      { "tour de Guetteracine^fd", 9 },
      { "bosquet d'Aigueracine^md", 8 },
      { "source d'Aigueracine^fd", 6 },
      { "chute des Rulanyil^fd", 2 },
      { "surplomb côtier^md", 2 },
      { "sanctuaire côtier^md", 8 },
      { "oratoire du sanctuaire côtier^md", 1 },
      { "grotte au serpent^fd", 8 },
      { "oratoire de la grotte au serpent^md", 1 },
      { "landes d'Ombrume^pfd", 8 },
      { "Recoin des ombres^md", 8 },
      { "Val coiffé^md", 8 },
      { "maisonnette du trameur^fd", 8 },
      { "Atronach^md", 4 },
      { "Serpent^md", 4 },
      { "Ombre^fd", 4 },
      { "Souracine^fd", 3 },
      { "panorama de Thondundor^md", 6 },
      { "val des cheminées de pierre^md", 2 },
      { "repos des deux chutes^md", 2 },
      { "fondrière du Verrant^fd", 8 },
      { "oratoire de la fondrière du Verrant^md", 1 },
      { "dolmen de la cour du Roi-Nature^md", 5 },
      { "Foyeraie^F", 8 },
      { "oratoire de Foyeraie^md", 1 },
   },
}

Harvest.poiData["malabaltor"] = {
--Malabal Tor (Aldmeri, lvl 31-37)
   ["malabaltor_base"] = { --Malabal Tor
      --fr
      { "Abamath^M", 8 },
      { "oratoire d'Abamath^md", 1 },
      { "comptoir de commerce Baandari^md", 8 },
      { "oratoire du comptoir Baandari^md", 1 },
      { "Belarata^F", 8 },
      { "détroit de Pointe-amère^fd", 6 },
      { "ruines de Roncenoire^pfd", 4 },
      { "vallée de Peinesang^fd", 8 },
      { "oratoire de la vallée de Peinesang^md", 1 },
      { "nid de Serre-os^md", 6 },
      { "dolmen de la Côte brisée^md", 5 },
      { "chœur de l'imploration divine^md", 9 },
      { "crique écarlate^fd", 3 },
      { "précipice de l'Homme mort^md", 3 },
      { "Noirbois^M", 8 },
      { "Dra'bul^F", 8 },
      { "oratoire de Dra'Bul^md", 1 },
      { "butte de Dugan^fd", 6 },
      { "Donjon : l'île des Tempêtes^md", 7 },
      { "site estival de Falinesti^md", 8 },
      { "îlot des quatre carrières^md", 2 },
      { "trouée de Fuller^fd", 8 },
      { "fosse aux vargrisons^fd", 3 },
      { "Île du fer à cheval^fd", 2 },
      { "ruines d'Ilayas^pfd", 8 },
      { "oratoire des ruines d'Ilayas^md", 1 },
      { "grotte accidentée^fd", 6 },
      { "Jathsogur^M", 8 },
      { "poche de Jode^fd", 8 },
      { "Dernière aventure de Matthilde^fd", 9 },
      { "bâillement d'Ogrim^md", 2 },
      { "Ouze^F", 8 },
      { "Ragnthar^F", 2 },
      { "berge^fd", 6 },
      { "racines de Silvenar^pfd", 3 },
      { "ruines de Shael^pfd", 3 },
      { "Silvenar^F", 8 },
      { "dolmen du val de Silvenar^md", 5 },
      { "surplomb du senche assoupi^md", 9 },
      { "Starwalk Cavern", 2 },
      { "Guetrangle^F", 2 },
      { "maison des suppliques^fd", 2 },
      { "Havremêle^F", 8 },
      { "Rituel^md", 4 },
      { "Voleur^md", 4 },
      { "Guerrier^md", 4 },
      { "tombeau des Apostats^md", 3 },
      { "Sylvanhenge^M", 8 },
      { "Gardeval^M", 8 },
      { "oratoire de Gardeval^md", 1 },
      { "Port Vélyn^M", 8 },
      { "oratoire de Port Vélyn^md", 1 },
      { "Gastefoule^M", 8 },
      { "oratoire de Gastefoule^md", 1 },
      { "Cours bondissant^md", 8 },
      { "oratoire du val du Cours bondissant^md", 1 },
      { "détroit de Percevent^md", 6 },
      { "dolmen du bassin du Xylo^md", 5 },
   },
}



Harvest.poiData["reapersmarch"] = {
--Reaper's March (Aldmeri, lvl 37-43)
   ["reapersmarch_base"] = {     --Reaper's March
      --fr
      { "Arenthia^F", 8 },
      { "oratoire d'Arenthia^md", 1 },
      { "vallée d'Ozur le gros^fd", 6 },
      { "arche brisée^fd", 9 },
      { "Coup de griffe^M", 3 },
      { "campement du croissant côtier^md", 2 },
      { "campement en ruines de Brassaube^md", 2 },
      { "Dolmen de Brassaube^md", 5 },
      { "camp des brigands de Brassaube^md", 2 },
      { "fosse de la litanie^fd", 6 },
      { "monastère de Do'Krin^md", 8 },
      { "Dune^F", 8 },
      { "oratoire de Dune^md", 1 },
      { "Donjon : toile de Sélène^md", 7 },
      { "folie de Fadir^fd", 3 },
      { "site automnal de Falinesti^md", 8 },
      { "quai de pêche^md", 2 },
      { "fort de la Veillée^md", 8 },
      { "oratoire du fort de la Veillée^md", 1 },
      { "fort Sphinx^md", 8 },
      { "oratoire du fort Sphinx^md", 1 },
      { "Verte-Motte^F", 8 },
      { "bosquet du parle-nature^md", 9 },
      { "caravane d'Hadran^fd", 8 },
      { "lumière de Jode^fd", 3 },
      { "dolmen du bois de Jode^md", 5 },
      { "galerie de Kuna^fd", 3 },
      { "campement d'Ozur le maigrichon^md", 2 },
      { "Mont-la-Lune^M", 8 },
      { "oratoire de Mont-la-Lune^md", 1 },
      { "dolmen de la forêt nord^md", 5 },
      { "quais de la vieille S'ren-ja^pmd", 6 },
      { "caverne de la vieille ville^fd", 9 },
      { "Pa'alat^F", 8 },
      { "Rawl'kha^F", 8 },
      { "oratoire de Rawl'kha^md", 1 },
      { "monument de la Camarde^md", 6 },
      { "campement du chercheur^md", 2 },
      { "S'ren-ja^M", 8 },
      { "Sénalana^F", 8 },
      { "oratoire de Sren-ja^md", 1 },
      { "Apprenti^md", 4 },
      { "Destrier^md", 4 },
      { "presbytère infâme^md", 3 },
      { "cairn de Thibaut^md", 3 },
      { "arène de Thizzrini^fd", 8 },
      { "Thormar^M", 8 },
      { "sentier des deux Lunes^md", 8 },
      { "repos d'Ushmal^md", 6 },
      { "village de Voileronce^md", 8 },
      { "oratoire de Voileronce^md", 1 },
      { "chutes des danseurs d'eau^pfd", 6 },
      { "caverne du Vent gémissant^fd", 3 },
      { "Folbosque^F", 8 },
      { "caverne de Folbosque^fd", 2 },
      { "oratoire de Folbosque^md", 1 },
      
   },
}

Harvest.poiData["rivenspire"] = {
--Rivenspire (Daggerfall, lvl 25-30)
   ["rivenspire_base"] = {       --Rivenspire
      --fr
      { "toile d'Aésar^fd", 6 },
      { "dolmen de Boralis^md", 5 },
      { "oratoire de Boralis^md", 1 },
      { "Bréagha-Fin^F", 8 },
      { "camp Tamrith^md", 8 },
      { "oratoire du camp Tamrith^md", 1 },
      { "Crêtombre^F", 8 },
      { "mine de Crêtombre^fd", 3 },
      { "oratoire de Crêtombre^md", 1 },
      { "ferme des Dorell^fd", 2 },
      { "Donjon : crypte des cœurs^md", 7 },
      { "grève d'Esteroche^fd", 6 },
      { "terres des Edrald^pfd", 8 },
      { "ruines d'Erokii^pfd", 3 },
      { "dolmen des plaines d'Euphraise^md", 5 },
      { "Défilé-du-déchu^M", 8 },
      { "oratoire de Défilé-du-déchu^md", 1 },
      { "catacombes de Gardecouleur^pfd", 3 },
      { "refuge secret d'Hildune^md", 3 },
      { "ferme des Hinault^fd", 8 },
      { "galgals de Givrosée^pmd", 8 },
      { "oratoire des galgals de Givrosée^md", 1 },
      { "perle de Lagra^fd", 2 },
      { "collines de Lorkrata^pfd", 8 },
      { "hantise de Magdalena^fd", 6 },
      { "espoir de Moira^md", 8 },
      { "Pointe-Nord^F", 8 },
      { "oratoire de Pointe-Nord^md", 1 },
      { "village de Norsalant^md", 2 },
      { "cicatrice obsidienne^fd", 3 },
      { "fort du Fiel aîné^md", 2 },
      { "fort de Kelgen l'ancien^md", 6 },
      { "ruines de l'ancienne Taillemont^pfd", 2 },
      { "oratoire de Vieusseuil^md", 1 },
      { "ruines du Doigt d'Orque^pfd", 3 },
      { "château Corbeguet^md", 8 },
      { "tertres sanguinaires^pmd", 8 },
      { "oratoire des tertres sanguinaires^md", 1 },
      { "grotte de Noirsort^fd", 2 },
      { "Taillemont^M", 8 },
      { "oratoire de Taillemont^md", 1 },
      { "oratoire du col voilé^md", 1 },
      { "val de Sabot-d'argent^md", 8 },
      { "crique des sirènes^fd", 6 },
      { "tour de Gardesud^fd", 2 },
      { "oratoire du site de rassemblement^md", 1 },
      { "Atronach^md", 4 },
      { "Morteroche^F", 8 },
      { "Serpent^md", 4 },
      { "Ombre^fd", 4 },
      { "repos du marchand^md", 9 },
      { "cheminée du Traître^fd", 8 },
      { "crypte des tribulations^fd", 3 },
      { "tour Guetteval^fd", 6 },
      { "Veawend Ede^M", 9 },
      { "dolmen de la lande d'Ouestemarche^md", 5 },
      { "phare zéphyréen^md", 9 },
      
   },
}

Harvest.poiData["shadowfen"] = {
--Shadowfen (Ebonheart, lvl 25-30)
   ["shadowfen_base"] = {        --Shadowfen
      --fr
      { "Alten Corimont^M", 8 },
      { "oratoire d'Alteri Corimont^md", 1 },
      { "ruines d'Atanaz^pfd", 3 },
      { "pierre de l'Atronach^fd", 4 }, --WTF?
      { "caverne d'aigracine^fd", 6 },
      { "Lisemère^F", 8 },
      { "oratoire de Lisemère^md", 1 },
      { "Défense brisée^F", 3 },
      { "camp abattoir de cristal^md", 2 },
      { "camp réduction charitable^md", 2 },
      { "camp collet-de-soie^md", 2 },
      { "navire du capitaine Os^md", 6 },
      { "ruines de Chid-Moska^pfd", 3 },
      { "Tombes profondes^pfd", 8 },
      { "Donjon : Arx Corinium^md", 7 },
      { "hameau abandonné^md", 8 },
      { "oratoire du hameau abandonné^md", 1 },
      { "ruines de Gandranen^pfd", 3 },
      { "bassins d'incubation^pm", 8 },
      { "oratoire des bassins d'incubation^md", 1 },
      { "couronne du couvain^fd", 9 },
      { "repaire d'Haynekhtnamet^md", 6 },
      { "Enclave abandonnée", 2 },
      { "Hissmir^M", 8 },
      { "oratoire d'Hissmir^md", 1 },
      { "dolmen de la Feuille détrempée^md", 5 },
      { "Loriasel^M", 8 },
      { "oratoire de Loriasel^md", 1 },
      { "village de Fangearbre^md", 8 },
      { "Obscuronde^F", 8 },
      { "Nen Ria^F", 6 },
      { "mine à kwamas d'Onkobra^fd", 3 },
      { "bourbier tamisé^md", 8 },
      { "oratoire du bourbier tamisé^md", 1 },
      { "dolmen de l'Échine réticulée^md", 5 },
      { "réaume de Sanghin^md", 3 },
      { "pierre du Serpent^fd", 4 }, --WTF
      { "autel de la Gueule noire^md", 3 },
      { "campement des esclavagistes^md", 6 },
      { "Inondelle^M", 8 },
      { "oratoire d'Inondelle^md", 1 },
      { "Fort-Tempête^M", 8 },
      { "oratoire de Fort-Tempête^md", 1 },
      { "grève de Solécaille^fd", 8 },
      { "camp d'acquisition de Telvanni^md", 2 },
      { "Ten-Maur-Wolk^M", 8 },
      { "Grâcieux dominateur^md", 2 },
      { "Ombre^fd", 4 },
      { "vil pavillon^md", 2 },
      { "Tsonashap^fd", 2 },
      { "dolmen du marécage venimeux^md", 5 },
      { "oratoire des marécages venimeux^md", 1 },
      { "chutes du wamasu triste^pfd", 9 },
      { "prison de Blanche-rose^fd", 8 },
      { "autel à Xal Haj-Ei^md", 9 },
      { "Xal Ithix^M", 8 },
      { "Xal Thak^M", 6 },
      { "Zuuk^M", 8 },
      
   },
}


Harvest.poiData["stonefalls"] = {
--Stonefalls (Ebonheart, lvl 5-15)
   ["stonefalls_base"] = {       --Stonefalls
      --fr
      { "soulèvement de l'armature^md", 9 },
      { "Mont cendreux^md", 8 },
      { "oratoire de la Route cendreuse^md", 1 },
      { "Frères de la discorde^mp", 8 },
      { "oratoire des Frères de la discorde^md", 1 },
      { "caverne des souvenirs^fd", 6 },
      { "bois du corbeau^md", 3 },
      { "dolmen de Daen Seeth^md", 5 },
      { "camp d'invasion de la Pointe de dague^md", 2 },
      { "ferme Davenas^fd", 2 },
      { "Guet de Davon^md", 8 },
      { "oratoire du Guet de Davon^md", 1 },
      { "quais^pm", 8 },
      { "Champignonnière^fd", 7 },
      { "Cœurébène^M", 8 },
      { "oratoire de Cœurébène^md", 1 },
      { "mine de Braisine^fd", 3 },
      { "Fort Arand^M", 8 },
      { "oratoire de Fort Arand^md", 1 },
      { "Fort Virak^M", 8 },
      { "oratoire de Fort Virak^md", 1 },
      { "chutes de Brumegrise^pfd", 2 },
      { "tour d'Heimlyn^fd", 8 },
      { "creux des marées^md", 3 },
      { "Hrogarheim^M", 8 },
      { "oratoire de Hrogarheim^md", 1 },
      { "temple d'Iliath^md", 8 },
      { "oratoire du temple d'Iliath^md", 1 },
      { "Nef de la mer intérieure^fd", 3 },
      { "lande de Kragen^fd", 8 },
      { "oratoire de la lande de Kragen^md", 1 },
      { "Lukiul Uxith^M", 8 },
      { "surplomb du cours de magma^md", 9 },
      { "nid de Méphala^md", 3 },
      { "Othrenis^M", 8 },
      { "oratoire d'Othrenis^md", 1 },
      { "plantation de Sathram^fd", 8 },
      { "oratoire de la Plantation de Sathram^md", 1 },
      { "Senie^M", 8 },
      { "oratoire de Senie^md", 1 },
      { "langue de Shéogorath^fd", 3 },
      { "détroit des épaves^md", 6 },
      { "autel frissonnant^md", 6 },
      { "caverne d'humus^fd", 3 },
      { "Plaines affamées^pfd", 8 },
      { "caverne des fumerolles^fd", 9 },
      { "campement du lac aux fumerolles^md", 2 },
      { "campement d'Eau-Dormante^md", 2 },
      { "île de Rochecroc^fd", 2 },
      { "ruche de Luttessaim^fd", 6 },
      { "mine à kwama de Luttessaim^fd", 2 },
      { "mares de soufre^fpd", 8 },
      { "oratoire des mares de soufre^md", 1 },
      { "bosquet des Brahma^md", 6 },
      { "port^md", 1 },
      { "Dame^fd", 4 },
      { "Amant^md", 4 },
      { "serre de la matrone^fd", 6 },
      { "Flèche tourmentée^fd", 8 },
      { "dolmen de Varanis^md", 5 },
      { "Ramure de Vivec^fd", 8 },
      { "oratoire de la Ramure de Vivec^md", 1 },
      { "dolmen de Zabamat^md", 5 },
      
   },
--Bal Foyen (Ebonheart lvl 1-5)
   ["balfoyen_base"] = {      --Bal Foyen
      --fr
      { "quais de Bal Foyen^pmd", 8 },
      { "Dhalmora^M", 8 },
      { "oratoire de Dhalmora^md", 1 },
      { "fort Zéren^md", 8 },
      { "oratoire de Fort Zeren^md", 1 },
      { "oratoire des quais de Foyen^md", 1 },
      { "site d'accostage de la dague dissimulée^md", 2 },
      { "surplomb de la pointe de la plantation^md", 2 },
   },

   
   
   --Bleakrock Isle (Ebonheart, lvl 1-5)
   
   
   
   
   ["bleakrock_base"] = {  --Bleakrock Isle
      --fr      
      { "village de Morneroc^md", 8 },
      { "oratoire de Morneroc^md", 1 },
      { "pointe des compagnons^fd", 2 },
      { "repaire de Griffemort^md", 2 },
      { "camp de Givremordant^md", 8 },
      { "maison d'Halmaéra^fd", 8 },
      { "Folie d'Hozzin^fd", 8 },
      { "camp des chasseurs^md", 8 },
      { "Trou d'Orkey^md", 8 },
      { "camp de pêche du Souqueur^md", 2 },
      { "Tertre des Nimbes^md", 8 },
   },
}





Harvest.poiData["stormhaven"] = {
--Stormhaven (Daggerfall, lvl 16-23)
   ["stormhaven_base"] = {       --Stormhaven
      --fr
      { "ferme abandonnée^fd", 6 },
      { "château d'Alcaire^md", 8 },
      { "oratoire du château d'Alcaire^md", 1 },
      { "dolmen d'Alcaire^md", 5 },
      { "autel antique^md", 6 },
      { "bastion d'Aphren^md", 8 },
      { "propriété at-Tura^fd", 8 },
      { "mine d'Ursegriffe^fd", 3 },
      { "ruines de l'Esquille^pfd", 3 },
      { "oratoire des ruines de l'Esquille^md", 1 },
      { "caverne des rêves^fd", 2 },
      { "chutes de Cumbrie^pfd", 2 },
      { "vigie de Cumbrie^fd", 8 },
      { "eaux des dreughs^pfd", 6 },
      { "Flanc-dreugh^M", 8 },
      { "oratoire de la plantation Dro'dara^md", 1 },
      { "plantation Dro'dara^fd", 8 },
      { "Donjon : égouts d'Haltevoie", 7 },
      { "galerie de Farangel^fd", 3 },
      { "plateau de Farangel^md", 8 },
      { "fort du Brandon^md", 8 },
      { "oratoire du fort du Brandon^md", 1 },
      { "île du pêcheur^fd", 9 },
      { "dolmen de Gavaudon^md", 5 },
      { "atelier Martelmort^md", 9 },
      { "phare de Koeglin^md", 8 },
      { "mine de Koeglin^fd", 3 },
      { "village de Koeglin^md", 8 },
      { "oratoire du village de Koeglin^md", 1 },
      { "dolmen de Ménévia^md", 5 },
      { "gouffre lunaire^md", 8 },
      { "plage aux vasards^fd", 6 },
      { "Roc du cauchemar^md", 2 },
      { "ruines de Norvulk^pfd", 3 },
      { "ferme des Nurin^fd", 8 },
      { "abbaye du Paria^fd", 8 },
      { "oratoire de l'abbaye du Paria^md", 1 },
      { "catacombes du Paria^pfd", 3 },
      { "vigie de Beigeport^fd", 3 },
      { "garde-manger de Scrag^md", 6 },
      { "escarpement de Shinji^md", 8 },
      { "autel à Azura^md", 2 },
      { "tour Absoute^fd", 8 },
      { "oratoire d'Absoute^md", 1 },
      { "nid d'araignée^md", 6 },
      { "ancrages de Seignacier^pmd", 8 },
      { "campement des gobelins Mâchepierres^md", 2 },
      { "campement des Rêveurs supernaux^md", 2 },
      { "Seigneur^md", 4 },
      { "Mage^md", 4 },
      { "Tour^fd", 4 },
      { "repos des voyageurs^md", 2 },
      { "ferme des Vanne^fd", 8 },
      { "oratoire d'Haltevoie^md", 1 },
      { "Géant éploré^md", 8 },
      { "oratoire du Géant éploré^md", 1 },
      { "fort Venteux^M", 228 },
      { "oratoire du fort Venteux", 1 },
      { "caverne de Ventecrête^fd", 8 },
      { "entrepôt de Ventecrête^md", 9 },
   },
}


Harvest.poiData["therift"] = {
--The Rift (Ebonheart, lvl 37-43)
   ["therift_base"] = {          --The Rift
      --fr
      { "campement abandonné^md", 6 },
      { "clairière de Vendombre^fd", 2 },
      { "Avancheznel^F", 3 },
      { "passe de l'Avalanche^fd", 8 },
      { "trou du Heaume fendu^md", 3 },
      { "Donjon : le Creuset béni^M", 7 },
      { "cachette d'Eldbjorg^fd", 9 },
      { "Dent de Faldar^fd", 3 },
      { "hall de Rochebrune^md", 8 },
      { "oratoire du hall de Rochebrune^md", 1 },
      { "Forelhost^M", 8 },
      { "fort Vallevert^M", 3 },
      { "ferme Givrelune^fd", 8 },
      { "ruines givrées^pfd", 6 },
      { "fort du Heaume^md", 8 },
      { "oratoire du fort du Heaume^md", 1 },
      { "demeure de Geirmund^fd", 8 },
      { "oratoire du hall de Geirmund^md", 1 },
      { "campement du géant^md", 6 },
      { "veille de Grethel^fd", 2 },
      { "colline de Brinectar^fd", 2 },
      { "tour d'Honrich^fd", 8 },
      { "oratoire de la tour d'Honrich^md", 1 },
      { "camp des chasseurs^md", 6 },
      { "Fort-Ivar^M", 8 },
      { "griffe de Jenedusil^fd", 2 },
      { "camp de Linèle Taille-crâne^md", 2 },
      { "Antre du lion^md", 3 },
      { "Mine perdue^fd", 8 },
      { "crête du mammouth^fd", 2 },
      { "Nimalten^F", 8 },
      { "oratoire de Nimalten^md", 1 },
      { "mine de la Galerne^fd", 8 },
      { "oratoire du la mine de la Galerne^md", 1 },
      { "grotte de Montpin^fd", 8 },
      { "dolmen des collines de Rochefendre^md", 5 },
      { "oratoire des collines de Rochefendre^md", 1 },
      { "Faillaise^F", 8 },
      { "oratoire de Faillaise^md", 1 },
      { "Pierre-de-Shor^fd", 8 },
      { "Tertre de Voile-foyer^md", 3 },
      { "Retraite du scalde^fd", 8 },
      { "oratoire de la Retraite du scalde^md", 1 },
      { "dolmen des pics de Fumegivre^md", 5 },
      { "vigie de Givrebrume^fd", 9 },
      { "grotte de Brisejambe^fd", 3 },
      { "dolmen du Bassin rocheux^md", 5 },
      { "Taarengrav^F", 8 },
      { "oratoire de Taarengrav^md", 1 },
      { "Apprenti^md", 4 },
      { "Destrier^md", 4 },
      { "campement des Trois tribus^md", 2 },
      { "ferme de Tréva^fd", 8 },
      { "Trolhetta^M", 8 },
      { "oratoire du sommet de Trolhetta^md", 1 },
      { "oratoire de Trolhetta^md", 1 },
      { "caverne des trolls^fd", 6 },
      { "ravin du Tueur de trolls^md", 9 },
      { "bois de Vernim^md", 8 },
      { "bosquet du feu follet^md", 6 },
      
   },
}

Harvest.poiData["craglorn"] = {
--craglorn
   ["craglorn_base"] = {          --craglorn
      --fr
   },
}

