Harvest.allLocalizations = {
    ["en"] = {
        ["filter1"] = "Metalworking",
        ["filtertooltip1"] = "Display ore on the map and compass.",
        ["import1"] = "Metalworking",
        ["impfiltertooltip1"] = "Display ore on the map and compass.",
        ["gather1"] = "Metalworking",
        ["gatfiltertooltip1"] = "Display ore on the map and compass.",
        ["filter2"] = "Clothier",
        ["filtertooltip2"] = "Display clothing material on the map and compass.",
        ["filter3"] = "Enchantment",
        ["filtertooltip3"] = "Display runestones on the map and compass.",
        ["filter4"] = "Alchemy",
        ["filtertooltip4"] = "Display herbs on the map and compass.",
        ["filter5"] = "Woodworking",
        ["filtertooltip5"] = "Display wood on the map and compass.",
        ["filter6"] = "Chests",
        ["filtertooltip6"] = "Display chests on the map and compass.",
        -- Originally 6 changed to 8 adding (7)solvents, (8)fish
        ["filter7"] = "Solvent",
        ["filtertooltip7"] = "Display solvents on the map and compass.",
        ["filter8"] = "Fish",
        ["filtertooltip8"] = "Display fish on the map and compass.",
        ["size1"] = "Pin size",
        ["sizetooltip1"] = "Set the size of the ore map pins.",
        ["size2"] = "Pin size",
        ["sizetooltip2"] = "Set the size of the clothing material map pins.",
        ["size3"] = "Pin size",
        ["sizetooltip3"] = "Set the size of the runstone map pins.",
        ["size4"] = "Pin size",
        ["sizetooltip4"] = "Set the size of the herb map pins.",
        ["size5"] = "Pin size",
        ["sizetooltip5"] = "Set the size of the wood map pins.",
        ["size6"] = "Pin size",
        ["sizetooltip6"] = "Set the size of the chest map pins.",
        -- Originally 6 changed to 8 adding (7)solvents, (8)fish
        ["size7"] = "Pin size",
        ["sizetooltip7"] = "Set the size of the solvents map pins.",
        ["size8"] = "Pin size",
        ["sizetooltip8"] = "Set the size of the fish map pins.",
        ["color1"] = "Pin color",
        ["colortooltip1"] = "Set the color of the ore map and compass pins.",
        ["color2"] = "Pin color",
        ["colortooltip2"] = "Set the color of the clothing material map and compass pins.",
        ["color3"] = "Pin color",
        ["colortooltip3"] = "Set the color of the runestone map and compass pins.",
        ["color4"] = "Pin color",
        ["colortooltip4"] = "Set the color of the herb map and compass pins.",
        ["color5"] = "Pin color",
        ["colortooltip5"] = "Set the color of the wood map and compass pins.",
        ["color6"] = "Pin color",
        ["colortooltip6"] = "Set the color of the chest map and compass pins.",
        -- Originally 6 changed to 8 adding (7)solvents, (8)fish
        ["color7"] = "Pin color",
        ["colortooltip7"] = "Set the color of the solvents map and compass pins.",
        ["color8"] = "Pin color",
        ["colortooltip8"] = "Set the color of the fish map and compass pins.",
        ["fov"] = "Field of View",
        ["fovtooltip"] = "25 ~ You can see pins 90° in front of you.\n(25% = a quarter of the circle)\n100 ~ You see every pin close to you.\n(100% = the whole circle).",
        ["distance"] = "Max pin distance",
        ["distancetooltip"] = "The maximum distance for pins to appear on the compass.",
        ["compass"] = "Enable compass",
        ["compasstooltip"] = "Enable the display of close pins on the compass.",
    },
    ["de"] = {
        ["filter1"] = "Schmied",
        ["filtertooltip1"] = "Zeige Erze auf der Karte und dem Kompass.",
        ["filter2"] = "Schneiderei",
        ["filtertooltip2"] = "Zeige Kleidungsmaterial auf der Karte und dem Kompass.",
        ["filter3"] = "Verzauberung",
        ["filtertooltip3"] = "Zeige Runen auf der Karte und dem Kompass.",
        ["filter4"] = "Alchemie",
        ["filtertooltip4"] = "Zeige Kräuter auf der Karte und dem Kompass.",
        ["filter5"] = "Schreinerei",
        ["filtertooltip5"] = "Zeige Holz auf der Karte und dem Kompass.",
        ["filter6"] = "Schatztruhen",
        ["filtertooltip6"] = "Zeige Schatztruhen auf der Karte und dem Kompass.",
        -- Originally 6 changed to 8 adding (7)solvents, (8)fish
        ["filter7"] = "Solvent",
        ["filtertooltip7"] = "Display solvents on the map and compass.",
        ["filter8"] = "Fish",
        ["filtertooltip8"] = "Display fish on the map and compass.",
        ["size1"] = "Pingröße",
        ["sizetooltip1"] = "Setze die Größe der Erzpins auf der Karte.",
        ["size2"] = "Pingröße",
        ["sizetooltip2"] = "Setze die Größe der Kleidungsmaterialpins auf der Karte.",
        ["size3"] = "Pingröße",
        ["sizetooltip3"] = "Setze die Größe der Runenpins auf der Karte.",
        ["size4"] = "Pingröße",
        ["sizetooltip4"] = "Setze die Größe der Kräuterpins auf der Karte.",
        ["size5"] = "Pingröße",
        ["sizetooltip5"] = "Setze die Größe der Holzpins auf der Karte.",
        ["size6"] = "Pingröße",
        ["sizetooltip6"] = "Setze die Größe der Truhenpins auf der Karte.",
        -- Originally 6 changed to 8 adding (7)solvents, (8)fish
        ["size7"] = "Pin size",
        ["sizetooltip7"] = "Set the size of the solvents map pins.",
        ["size8"] = "Pin size",
        ["sizetooltip8"] = "Set the size of the fish map pins.",
        ["color1"] = "Pinfarbe",
        ["colortooltip1"] = "Setze die Farbe der Erzpins auf der Karte und dem Kompass.",
        ["color2"] ="Pinfarbe",
        ["colortooltip2"] = "Setze die Farbe der Kleidungsmaterialpins auf der Karte und dem Kompass.",
        ["color3"] = "Pinfarbe",
        ["colortooltip3"] = "Setze die Farbe der Runenpins auf der Karte und dem Kompass.",
        ["color4"] = "Pinfarbe",
        ["colortooltip4"] = "Setze die Farbe der Kräuterpins auf der Karte und dem Kompass.",
        ["color5"] = "Pinfarbe",
        ["colortooltip5"] = "Setze die Farbe der Holzpins auf der Karte und dem Kompass.",
        ["color6"] = "Pinfarbe",
        ["colortooltip6"] = "Setze die Farbe der Truhenpins auf der Karte und dem Kompass.",
        -- Originally 6 changed to 8 adding (7)solvents, (8)fish
        ["color7"] = "Pin color",
        ["colortooltip7"] = "Set the color of the solvents map and compass pins.",
        ["color8"] = "Pin color",
        ["colortooltip8"] = "Set the color of the fish map and compass pins.",
        ["fov"] = "Sichtbereich",
        ["fovtooltip"] = "0.25 ~ Du siehst Pins innerhalb von 90° vor dir. (25% = ein Viertel des Kreises).\n1 ~ Du siehst alle Pins um dich herum. (100% = der gesammte Kreis).",
        ["distance"] = "Reichweite",
        ["distancetooltip"] = "Die maximale Distanz für Pins, um auf dem Kompass zu erscheinen.",
        ["compass"] = "Aktiviere Kompass",
        ["compasstooltip"] = "Aktiviere das Anzeigen von nahen Pins auf dem Kompass.",
    },
    ["fr"] = { --translation by wookiefrag
        ["filter1"] = "Forge : Gisements",
        ["filtertooltip1"] = "Montre les gisements de minerais sur la carte et la boussole.",
        ["filter2"] = "Couture : Matériaux",
        ["filtertooltip2"] = "Montre les matériaux de couture sur la carte et la boussole.",
        ["filter3"] = "Enchantement : Pierres runiques",
        ["filtertooltip3"] = "Montre les pierres runiques sur la carte et la boussole.",
        ["filter4"] = "Alchimie : Plantes et Solvants",
        ["filtertooltip4"] = "Montre les plantes et les solvants sur la carte et la boussole.",
        ["filter5"] = "Travail du bois : Matériaux",
        ["filtertooltip5"] = "Montre les rondins de bois sur la carte et la boussole.",
        ["filter6"] = "Coffres",
        ["filtertooltip6"] = "Montre les coffres sur la carte et la boussole.",
        -- Originally 6 changed to 8 adding (7)solvents, (8)fish
    ["filter7"] = "Solvent",
        ["filtertooltip7"] = "Display solvents on the map and compass.",
        ["filter8"] = "Fish",
        ["filtertooltip8"] = "Display fish on the map and compass.",
        ["size1"] = "Taille des repères",
        ["sizetooltip1"] = "Paramètre la taille des repères de gisements de la carte.",
        ["size2"] = "Taille des repères",
        ["sizetooltip2"] = "Paramètre la taille des repères de matériaux de couture de la carte.",
        ["size3"] = "Taille des repères",
        ["sizetooltip3"] = "Paramètre la taille des repères de pierres runiques de la carte.",
        ["size4"] = "Taille des repères",
        ["sizetooltip4"] = "Paramètre la taille des repères de plantes de la carte.",
        ["size5"] = "Taille des repères",
        ["sizetooltip5"] = "Paramètre la taille des repères de rondins de bois de la carte.",
        ["size6"] = "Taille des repères",
        ["sizetooltip6"] = "Paramètre la taille des repères de coffres de la carte.",
        -- Originally 6 changed to 8 adding (7)solvents, (8)fish
        ["size7"] = "Pin size",
        ["sizetooltip7"] = "Set the size of the solvents map pins.",
        ["size8"] = "Pin size",
        ["sizetooltip8"] = "Set the size of the fish map pins.",
        ["color1"] = "Couleur des repères",
        ["colortooltip1"] = "Définit la couleur des repères de gisements de la carte et de la boussole.",
        ["color2"] = "Couleur des repères",
        ["colortooltip2"] = "Définit la couleur des repères de matériaux de couture de la carte et de la boussole.",
        ["color3"] = "Couleur des repères",
        ["colortooltip3"] = "Définit la couleur des repères de pierres runiques de la carte et de la boussole.",
        ["color4"] = "Couleur des repères",
        ["colortooltip4"] = "Définit la couleur des repères de plantes et solvants de la carte et de la boussole.",
        ["color5"] = "Couleur des repères",
        ["colortooltip5"] = "Définit la couleur des repères de rondins de bois de la carte et de la boussole.",
        ["color6"] = "Couleur des repères",
        ["colortooltip6"] = "Définit la couleur des repères de coffres de la carte et de la boussole.",
        -- Originally 6 changed to 8 adding (7)solvents, (8)fish
        ["color7"] = "Pin color",
        ["colortooltip7"] = "Set the color of the solvents map and compass pins.",
        ["color8"] = "Pin color",
        ["colortooltip8"] = "Set the color of the fish map and compass pins.",
        ["fov"] = "Champ de vision",
        ["fovtooltip"] = "25 ~ Vous voyez les repères a 90° en face de vous. (25% = un quart de cercle)\n100 ~ Vous voyez tous les repères autour de vous. (100% = un cercle entier).",
        ["distance"] = "Distance maximale d'un repère",
        ["distancetooltip"] = "Distance maximale a laquelle les différents repères apparaissent sur la boussole.",
        ["compass"] = "Activer la boussole",
        ["compasstooltip"] = "Activer l'affichage des repères a proximité sur la boussole.",
    }
}

-- Set Localization
Harvest.language = (GetCVar("language.2") or "en")
Harvest.localization = Harvest.allLocalizations[Harvest.language]
